### ISSUE TITLE
Refactor Family Parent ID to reflect Person.ID instead of Family_Tree.ID

### ISSUE THREAD

**Issue by owenbean400** [owenbean400/RecipeRootsSQL#29]
![Screenshot 2023-11-05 at 8 02 01 PM](https://github.com/owenbean400/RecipeRootsSQL/assets/63262699/f04332fd-e326-4957-95a4-4125d2f3a875)

**Comment by sheaDurgin** [comment]
Fixed in pull quest "Query for person tree" #31
